app/organization/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, Email


class RegisterOrganizationForm(FlaskForm):
    name = StringField('Organization Name', render_kw={"placeholder": "Organization Name"},
                       validators=[DataRequired(), Length(1, 64)])
    teacher = StringField('Organization Teacher', render_kw={"placeholder": "Organization Teacher"},
                          validators=[DataRequired(), Length(1, 64)])
    leader = StringField('Organization Leader Student', render_kw={"placeholder": "Organization Leader Student"},
                         validators=[DataRequired(), Length(1, 64)])
    email = StringField('Organization Email', render_kw={"placeholder": "Organization Email"},
                        validators=[DataRequired(), Length(1, 64), Email()])
    college = StringField('College', render_kw={"placeholder": "College or BJUT"},
                          validators=[DataRequired(), Length(1, 64)])
    phone = StringField('Contact Number', render_kw={"placeholder": "Contact Number"},
                        validators=[DataRequired(), Length(1, 64)])
    submit = SubmitField('Submit')

app/organization/__init__.py
from flask import Blueprint

organization = Blueprint('organization', __name__)

from . import views

app/organization/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user, login_required
from datetime import datetime
from . import organization
from .. import db
from ..decorators import permission_required
from ..models import Organization, User, Activity, Permission
from ..email import send_email
from .forms import RegisterOrganizationForm


@organization.route('/register', methods=['GET', 'POST'])
def register_organization():
    form = RegisterOrganizationForm()
    if form.validate_on_submit():
        email_find = User.query.filter_by(email=form.email.data).first()
        if email_find is not None:
            flash("Your email has been registered, please change your email")
            return render_template('organization/organization_register.html', form=form)
        username_find = User.query.filter_by(username=form.name.data).first()
        if username_find is not None:
            flash("Your organization name has been registered, please change your username")
            return render_template('organization/organization_register.html', form=form)
        organization = Organization(name=form.name.data,
                                    teacher=form.teacher.data,
                                    leader_student=form.leader.data,
                                    phone=form.phone.data,
                                    college=form.college.data,
                                    email=form.email.data
                                    )
        db.session.add(organization)
        db.session.commit()
        token = organization.generate_confirmation_token()
        send_email('sefbjut@163.com', 'Register Organization',
                   'mail_organization/To_administrator', organization=organization, token=token)
        flash('A register organization-account email has been sent to administrator.')
        return redirect(url_for('auth.login'))
    return render_template('organization/organization_register.html', form=form)


@organization.route('/send_result/<oid>', methods=['GET', 'POST'])
def send_result(oid):
    return render_template('organization/send_result.html', oid=oid)


@organization.route('/register_success/<oid>', methods=['GET'])
def register_success(oid):
    organization = Organization.query.filter_by(id=oid).first()
    user = User(student_id=organization.id,
                ID_number=organization.id,
                confirmed=True,
                email=organization.email,
                username=organization.name,
                password='password',
                avatar_img='/static/Image/ico.jpeg'
                )
    db.session.add(user)
    db.session.commit()
    thisUser = User.query.filter_by(ID_number=organization.id).first()
    thisUser.role_id = 2;
    db.session.add(thisUser)
    db.session.commit()
    # 注册时发送邮箱认证
    token = organization.generate_confirmation_token()
    send_email(organization.email, 'Register Organization Success',
               'mail_organization/success_register', user=user, token=token)
    flash('A register_success email has been sent to organization by email.')
    return redirect(url_for('auth.login'))


@organization.route('/register_fail/<oid>', methods=['GET'])
def result_fail(oid):
    organization = Organization.query.filter_by(id=oid).first()
    token = organization.generate_confirmation_token()
    send_email(organization.email, 'Register Organization Fail',
               'mail_organization/fail_register', token=token)
    flash('A register_fail email has been sent to organization by email.')
    return redirect(url_for('auth.login'))


@organization.route('/new_activity', methods=['GET', 'POST'])
def organization_activity():
    if request.method == 'GET':
        return render_template('organization/new_activity.html')
    if request.method == 'POST':
        if request.form["is"] == "Yes":
            is_Agree = True
        else:
            is_Agree = False
        string = request.form["activity_time"]
        name = request.form["activity_name"]
        place = request.form["activity_place"]
        describe = request.form["activity_describe"]
        organizer = request.form["organizer"]
        if name == "" or place == "" or string == "" or describe == "" or organizer == "":
            flash("Activity information cannot be empty")
            return render_template('organization/new_activity.html')
        time_str = string
        time = datetime.strptime(time_str, '%Y-%m-%dT%H:%M')
        acti = Activity(activity_name=name,
                        activity_time=time,
                        activity_place=place,
                        activity_describe=describe,
                        Organizer=organizer,
                        is_schoolAgree=is_Agree,
                        announcer_id=current_user.id
                        )
        db.session.add(acti)
        db.session.commit()
        flash('Your Activity Announcement has been released!')
        return redirect(url_for('main.index_activity'))


@organization.route('/want/<activity_id>')
@login_required
@permission_required(Permission.FOLLOW)
def want(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    if activity is None:
        flash('Invalid activity.')
        return redirect(url_for('main.index_activity'))
    if current_user.is_wanting(activity):
        flash('You are already wanting this post.')
        return redirect(url_for('main.index_activity'))
    current_user.want(activity)
    activity.want(current_user)
    db.session.commit()
    flash('You are now wanting this post')
    return redirect(url_for('main.index_activity'))


@organization.route('/not_want/<activity_id>')
@login_required
@permission_required(Permission.FOLLOW)
def not_want(activity_id):
    activity = Activity.query.filter_by(id=activity_id).first()
    if activity is None:
        flash('Invalid activity.')
        return redirect(url_for('main.index_activity'))
    if not current_user.is_wanting(activity):
        flash('You are not wanting this post.')
        return redirect(url_for('main.index_activity'))
    current_user.not_want(activity)
    activity.not_want(current_user)
    db.session.commit()
    flash('You are not wanting this post')
    return redirect(url_for('main.index_activity'))


@organization.route('/delete_transaction/<int:activity_id>')
@login_required
def delete_activity(activity_id):
    activity = Activity.query.get_or_404(activity_id)
    if current_user == activity.announcer:
        db.session.delete(activity)
        db.session.commit()
        flash('The activity has been deleted.')
        return redirect(url_for('main.user', username=activity.announcer.username))
    else:
        flash('你没有删评论权限')
        return redirect(url_for('main.user', username=activity.announcer.username))

app/templates/organization/_activities.html
<li class="avtivity" id="{{  avtivity.id }}">
    <div class="panel panel-warning">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <h3 class="item-name" style="display: inline">
                {{ avtivity.activity_name }}
            </h3>
            {% if avtivity.is_invalid %}
                <h2 style="display: inline; float: right">The event has expired!</h2>
            {% endif %}
        </div>
        <div class="panel-body">
            <p><strong>Details:</strong>{{ avtivity.activity_describe }}</p>
        </div>
        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><strong>Time</strong> {{ avtivity.activity_time }}</li>
            <li class="list-group-item"><strong>Place</strong> {{ avtivity.activity_place }}</li>
            <li class="list-group-item"><strong>Organizer:</strong> {{ avtivity.Organizer }}</li>
            <li class="list-group-item"><strong>Whether it is approved by the school:</strong>
                {% if avtivity.is_schoolAgree %}
                    Yes!
                {% else %}
                    No
                {% endif %}
            </li>
        </ul>

        <div class="panel-footer">
             <a class="head-photo" href="{{ url_for('.user', username=avtivity.announcer.username) }}">
                 {% if avtivity.announcer.avatar_img %}
                     <img class="img-rounded profile-thumbnail" src="{{ avtivity.announcer.avatar_img }}" alt="avatar"  style="width: 25px; height: 25px">
                 {% else %}
                     <img class="img-rounded profile-thumbnail" src="{{ avtivity.announcer.gravatar(size=25) }}" alt="avatar">
                 {% endif %}
            </a>
            <span class="post-author">
                <a href="{{ url_for('.user', username=avtivity.announcer.username) }}">
                    {{ avtivity.announcer.username }}
                    {% if avtivity.announcer.can(Permission.ACTIVITY) %}
                        <svg class="icon" viewBox="0 0 1024 1024" width="14" height="14" style="margin: 0;">
                            <path d="M959.786667 148.906667l-44.330667-0.725333c-1.024 0-100.437333-2.048-203.050667-41.728-105.301333-40.789333-173.141333-87.552-173.781333-88.021333L511.872 0 485.248 18.474667C484.608 18.901333 416.768 65.706667 311.466667 106.453333 208.938667 146.218667 109.482667 148.181333 108.544 148.181333L64 148.906667l0 430.464C64 795.477333 355.328 1024 511.957333 1024 668.714667 1024 960 795.477333 960 579.370667L959.786667 148.906667zM321.877333 772.48 321.877333 355.413333 282.112 355.413333 282.112 317.482667 441.173333 317.482667l0 189.610667 200.192-189.610667 157.696 0L321.877333 772.48z" fill="#3688FF"></path>
                        </svg>
                    {% endif %}
                </a>
            </span>
            <span class="post-date">{{ moment(avtivity.timestamp).fromNow() }}</span>

            {% if not current_user.is_wanting(avtivity) %}
                <a class="icon-btn" style="float:right; margin-right: 15px" href="{{ url_for('organization.want', activity_id=avtivity.id) }}#{{ avtivity.id }}">
                    <span class="glyphicon glyphicon-heart-empty"></span>
                    <span>{{ avtivity.wanter.count() }} WantToGo</span>
                </a>
            {% else %}
                <a class="icon-btn" style="float:right; margin-right: 15px" href="{{ url_for('organization.not_want', activity_id=avtivity.id) }}#{{ avtivity.id }}">
                    <span class="glyphicon glyphicon-heart"></span>
                    <span>{{ avtivity.wanter.count() }} WantToGo</span>
                </a>
            {% endif %}
        </div>
    </div>
</li>

app/templates/organization/_activitiesInProfile.html
<ul class="posts list-unstyled">
    {% for avtivity in activities %}
        <li class="avtivity" id="{{  avtivity.id }}">
        <div class="col-md-12">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading">
                    <h3 class="item-name" style="display: inline">
                        {{ avtivity.activity_name }}
                    </h3>
                </div>
                <div class="panel-body">
                    <p><strong>Details:</strong>{{ avtivity.activity_describe }}</p>
                </div>
                <!-- List group -->
                <ul class="list-group">
                    <li class="list-group-item"><strong>Time</strong> {{ avtivity.activity_time }}</li>
                    <li class="list-group-item"><strong>Place</strong> {{ avtivity.activity_place }}</li>
                    <li class="list-group-item"><strong>Organizer:</strong> {{ avtivity.Organizer }}</li>
                    <li class="list-group-item"><strong>Whether it is approved by the school:</strong>
                        {% if avtivity.is_schoolAgree %}
                            Yes!
                        {% else %}
                            No
                        {% endif %}
                    </li>
                </ul>

                <div class="panel-footer">
                    <span class="post-date">{{ moment(avtivity.timestamp).fromNow() }}</span>

                {#            删除#}
                    {% if current_user == avtivity.announcer %}
                            <a class="icon-btn" href="{{ url_for('organization.delete_activity', activity_id=avtivity.id)}}">
                                <span class="glyphicon glyphicon-trash"></span>
                                <span>delete</span>
                            </a>
                    {% endif %}
                </div>
            </div>
        </div>
        </li>
    {% endfor %}
</ul>

app/templates/organization/_activitiesWantingInProfile.html
<li class="avtivity" id="{{  want.wanted_Activity.id }}">
    <div class="panel panel-warning">
        <!-- Default panel contents -->
        <div class="panel-heading">
            <h3 class="item-name" style="display: inline">
                {{ want.wanted_Activity.activity_name }}
            </h3>
            {% if want.wanted_Activity.is_invalid %}
                <h2 style="display: inline; float: right">The event has expired!</h2>
            {% endif %}
        </div>
        <div class="panel-body">
            <p><strong>Details:</strong>{{ want.wanted_Activity.activity_describe }}</p>
        </div>
        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><strong>Time</strong> {{ want.wanted_Activity.activity_time }}</li>
            <li class="list-group-item"><strong>Place</strong> {{ want.wanted_Activity.activity_place }}</li>
            <li class="list-group-item"><strong>Organizer:</strong> {{ want.wanted_Activity.Organizer }}</li>
            <li class="list-group-item"><strong>Whether it is approved by the school:</strong>
                {% if want.wanted_Activity.is_schoolAgree %}
                    Yes!
                {% else %}
                    No
                {% endif %}
            </li>
        </ul>

        <div class="panel-footer">
             <a class="head-photo" href="{{ url_for('.user', username=want.wanted_Activity.announcer.username) }}">
                 {% if want.wanted_Activity.announcer.avatar_img %}
                     <img class="img-rounded profile-thumbnail" src="{{ want.wanted_Activity.announcer.avatar_img }}" alt="avatar"  style="width: 25px; height: 25px">
                 {% else %}
                     <img class="img-rounded profile-thumbnail" src="{{ want.wanted_Activity.announcer.gravatar(size=25) }}" alt="avatar">
                 {% endif %}
            </a>
            <span class="post-author">
                <a href="{{ url_for('.user', username=want.wanted_Activity.announcer.username) }}">
                    {{ want.wanted_Activity.announcer.username }}
                    {% if want.wanted_Activity.announcer.can(Permission.ACTIVITY) %}
                        <svg class="icon" viewBox="0 0 1024 1024" width="16" height="16" style="margin: 0">
                            <path d="M959.786667 148.906667l-44.330667-0.725333c-1.024 0-100.437333-2.048-203.050667-41.728-105.301333-40.789333-173.141333-87.552-173.781333-88.021333L511.872 0 485.248 18.474667C484.608 18.901333 416.768 65.706667 311.466667 106.453333 208.938667 146.218667 109.482667 148.181333 108.544 148.181333L64 148.906667l0 430.464C64 795.477333 355.328 1024 511.957333 1024 668.714667 1024 960 795.477333 960 579.370667L959.786667 148.906667zM321.877333 772.48 321.877333 355.413333 282.112 355.413333 282.112 317.482667 441.173333 317.482667l0 189.610667 200.192-189.610667 157.696 0L321.877333 772.48z" fill="#3688FF"></path>
                        </svg>
                    {% endif %}
                </a>
            </span>

            <span class="date" style="float: right">
                <span class="glyphicon glyphicon-time"></span>
                {{ moment(want.wanted_Activity.timestamp).fromNow() }}
            </span>
        </div>
    </div>
</li>

app/templates/organization/new_activity.html
{% extends "base.html" %}


{% block title %}New Organization Activity{% endblock %}


{% block head %}
{{ super() }}
    <!--     Custom styles for this template -->
    <link href="{{ url_for('static',filename='new-activity.css') }}" rel="stylesheet">
{% endblock %}


{% block page_content %}



    <div class="container">
        <div class="col-md-12">

    <!--        左侧表单-->
            <div class="col-md-6">
                <form class="form-activity form-horizontal" method="post">
                    <h1 class="form-activity-heading col-sm-offset-1">Activity</h1>
<!--                    活动名称-->
                    <div class="form-group">
                        <label for="activity_name" class="col-sm-offset-1 col-sm-3">Activity Name</label>
                        <div class="col-sm-8">
                            <input name="activity_name" id="activity_name" type="text" class="form-control" placeholder="Activity Name">
                        </div>
                    </div>
<!--                    活动时间-->
                    <div class="form-group">
                        <label for="activity_time" class="col-sm-offset-1 col-sm-3">Activity Time</label>
                        <div class="col-sm-8">
                            <input name="activity_time" id="activity_time" type="datetime-local" class="form-control" placeholder="Activity Time">
                        </div>
                    </div>
<!--                    活动地点-->
                    <div class="form-group">
                        <label for="activity_place" class="col-sm-offset-1 col-sm-3">Activity Place</label>
                        <div class="col-sm-8">
                            <input name="activity_place" id="activity_place" type="text" class="form-control" placeholder="Activity Place">
                        </div>
                    </div>
<!--                    活动描述-->
                    <div class="form-group">
                        <label for="activity_describe" class="col-sm-offset-1 col-sm-3">Activity Describe</label>
                        <div class="col-sm-8">
                            <textarea name="activity_describe" id="activity_describe" class="form-control describe" rows="3" placeholder="Activity Describe"></textarea>
                        </div>
                    </div>
<!--                    组织者-->
                    <div class="form-group">
                        <label for="organizer" class="col-sm-offset-1 col-sm-3">Organizer</label>
                        <div class="col-sm-8">
                            <input name="organizer" id="organizer" type="text" class="form-control" placeholder="Organizer">
                        </div>
                    </div>
<!--                    是否获批-->
                    <div class="form-group">
                        <label for="is" class="col-sm-offset-1 col-sm-3">Whether approved by the school</label>
                        <div class="col-sm-8">
                            <select name="is" id="is" class="form-control">
                                        <option selected="selected" value=""></option>
                                        <option>Yes</option>
                                        <option>No</option>
                            </select>
                        </div>
                    </div>
<!--                    提交表单-->
                    <div class="col-sm-offset-4 col-sm-7">
                        <button type="submit" class="btn btn-success active-submit" id="submit" >Submit</button>
                    </div>
                </form>
            </div>

            <!--        右侧图片-->
            <div class="col-md-6 decorate-photo">
            </div>
        </div>
    </div>

{% endblock %}

app/templates/organization/organization_register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Organization Register{% endblock %}


{% block head %}
{{ super() }}
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='bg.css') }}" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="onepage">
        <div class = "onepage-bg" id = "onepagebg">

{#        导航栏#}
            <nav calss="navbar navbar-inverse bg-light " role="navigation" style="background-color: rgba(245,245,245,0.7);">
                <div class="container">
{#                    头部#}
                    <div class="navbar-header">
                        <button type="button" class=" btn-warning navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Student Exchange Forum of BJUT</a>
                    </div>

{#                    尾部#}
                    <div class="collapse navbar-collapse">

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                 <a class="btn ref-signup chose" href="/auth/register">
                                 Register
                                 </a>
                             </li>
                        </div>

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                <a  class="btn ref-signup chose" href="/auth/login">
                                    Signin
                                </a>
                            </li>
                        </div>

                    </div>

                </div>
            </nav>


            <div class="container">

                <!--    flash消息显示区-->
                {% for message in get_flashed_messages() %}
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8 alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    <div class="col-sm-2">
                    </div>
                {% endfor %}

                <form role="form" class="form-signin" method="post" style="margin: 120px auto 0px auto;">
                    <h2 class="form-signin-heading">Organization Register</h2>

                    {{ form.csrf_token }}
                    {{ form.name }}
                    {{ form.teacher }}
                    {{ form.leader }}
                    {{ form.email }}
                    {{ form.college }}
                    {{ form.phone }}
                    <p id="p1"></p>
                    {{ form.submit }}
                </form>
            </div>
        </div>
</div>


<script>
        {#只要有id就能改#}
        document.getElementById('name').className = 'form-control'
        document.getElementById('teacher').className = 'form-control'
        document.getElementById('leader').className = 'form-control'
        document.getElementById('email').className = 'form-control'
        document.getElementById('phone').className = 'form-control'
        document.getElementById('college').className = 'form-control'

        var submit = document.getElementById('submit')
        submit.className = 'btn btn-lg btn-warning btn-block chose';
</script>



{% endblock %}

app/templates/organization/send_result.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block title %}Send Register Result{% endblock %}


{% block head %}
{{ super() }}
    <!-- 新 Bootstrap 核心 CSS 文件 -->
    <link href="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='signin.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='bg.css') }}" rel="stylesheet">
{% endblock %}


{% block body %}

<div class="onepage">
        <div class = "onepage-bg" id = "onepagebg">

            <nav calss="navbar navbar-inverse bg-light " role="navigation" style="background-color: rgba(245,245,245,0.7);">
                <div class="container">
{#                    头部#}
                    <div class="navbar-header">
                        <button type="button" class=" btn-warning navbar-toggle " data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a href="/" class="navbar-brand">Student Exchange Forum of BJUT</a>
                    </div>

{#                    尾部#}
                    <div class="collapse navbar-collapse">

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                 <a class="btn ref-signup chose" href="/auth/register">
                                 Register
                                 </a>
                             </li>
                        </div>

                        <div class="nav navbar-nav navbar-right">
                            <li class="chose">
                                <a  class="btn ref-signup chose" href="/auth/login">
                                    Signin
                                </a>
                            </li>
                        </div>

                    </div>

                </div>
            </nav>


            <div class="container">

                <!--    flash消息显示区-->
                {% for message in get_flashed_messages() %}
                    <div class="col-sm-2">
                    </div>
                    <div class="col-sm-8 alert alert-warning">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        {{ message }}
                    </div>
                    <div class="col-sm-2">
                    </div>
                {% endfor %}

                <form role="form" class="form-signin" method="post" style="margin: 120px auto 0px auto;">
                    <h2 class="form-signin-heading">Send Result Email</h2>
                    <a class="btn btn-lg btn-warning btn-block chose" href="{{ url_for('organization.register_success', oid=oid) }}">Register Success</a>
                    <a class="btn btn-lg btn-warning btn-block chose" href="{{ url_for('organization.result_fail', oid=oid) }}">Register Fail</a>
                </form>
            </div>
        </div>
</div>
{% endblock %}